import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '@/lib/api';
import { formatPesewas } from '@cedisense/shared';
import type { InsightsData } from '@cedisense/shared';
import '@/styles/print.css';

function getCurrentMonth(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
}

function formatMonthLabel(month: string): string {
  const [year, mon] = month.split('-').map(Number);
  const d = new Date(year, mon - 1, 1);
  return new Intl.DateTimeFormat('en-GB', { month: 'long', year: 'numeric' }).format(d);
}

export function MonthlyReportPrint() {
  const [searchParams] = useSearchParams();
  const month = searchParams.get('month') ?? getCurrentMonth();
  const [data, setData] = useState<InsightsData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api
      .get<InsightsData>(`/insights?month=${month}`)
      .then((d) => {
        setData(d);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [month]);

  useEffect(() => {
    if (data && !loading) {
      const t = setTimeout(() => window.print(), 500);
      return () => clearTimeout(t);
    }
  }, [data, loading]);

  if (loading) return <p style={{ padding: 24 }}>Loading report...</p>;
  if (!data) return <p style={{ padding: 24 }}>Failed to load report data.</p>;

  const net = data.current.total_income_pesewas - data.current.total_expenses_pesewas;

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: 24 }}>
      <h1>CediSense Monthly Report</h1>
      <p className="subtitle">{formatMonthLabel(month)}</p>

      <h2>Summary</h2>
      <table>
        <thead>
          <tr>
            <th>Metric</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Income</td>
            <td className="text-credit">{formatPesewas(data.current.total_income_pesewas)}</td>
          </tr>
          <tr>
            <td>Expenses</td>
            <td className="text-debit">{formatPesewas(data.current.total_expenses_pesewas)}</td>
          </tr>
          <tr>
            <td>Fees</td>
            <td>{formatPesewas(data.current.total_fees_pesewas)}</td>
          </tr>
          <tr className="total-row">
            <td>Net</td>
            <td className={net >= 0 ? 'text-credit' : 'text-debit'}>
              {net >= 0 ? '+' : '-'}
              {formatPesewas(Math.abs(net))}
            </td>
          </tr>
          <tr>
            <td>Transactions</td>
            <td>{data.current.transaction_count}</td>
          </tr>
        </tbody>
      </table>

      <h2>Spending by Category</h2>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Current Month</th>
            <th>Previous Month</th>
            <th>Change</th>
          </tr>
        </thead>
        <tbody>
          {data.category_trends.slice(0, 10).map((cat) => (
            <tr key={cat.category_id}>
              <td>
                {cat.icon} {cat.name}
              </td>
              <td>{formatPesewas(cat.current_pesewas)}</td>
              <td>{formatPesewas(cat.previous_pesewas)}</td>
              <td className={cat.change_pesewas <= 0 ? 'text-credit' : 'text-debit'}>
                {cat.change_percentage > 0 ? '+' : ''}
                {cat.change_percentage.toFixed(1)}%
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <p style={{ marginTop: 32, fontSize: 10, color: '#999' }}>
        Generated by CediSense — Built by Hodges &amp; Co.
      </p>
    </div>
  );
}
