import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '@/lib/api';
import { formatPesewas } from '@cedisense/shared';
import type { Transaction, Category } from '@cedisense/shared';
import '@/styles/print.css';

function formatDate(dateStr: string): string {
  return new Date(dateStr.slice(0, 10) + 'T00:00:00').toLocaleDateString('en-GH', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

function formatDateRange(from: string, to: string): string {
  if (from && to) return `${formatDate(from)} – ${formatDate(to)}`;
  if (from) return `From ${formatDate(from)}`;
  if (to) return `Up to ${formatDate(to)}`;
  return 'All time';
}

export function TransactionsPrint() {
  const [searchParams] = useSearchParams();
  const accountId = searchParams.get('account_id') ?? '';
  const categoryId = searchParams.get('category_id') ?? '';
  const from = searchParams.get('from') ?? '';
  const to = searchParams.get('to') ?? '';

  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    const txnParams = new URLSearchParams();
    txnParams.set('limit', '500');
    if (accountId) txnParams.set('account_id', accountId);
    if (categoryId) txnParams.set('category_id', categoryId);
    if (from) txnParams.set('from', from);
    if (to) txnParams.set('to', to);

    Promise.all([
      api.get<Transaction[]>(`/transactions?${txnParams.toString()}`),
      api.get<Category[]>('/categories'),
    ])
      .then(([txns, cats]) => {
        setTransactions(txns);
        setCategories(cats);
        setLoading(false);
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      });
  }, [accountId, categoryId, from, to]);

  useEffect(() => {
    if (!loading && !error && transactions.length > 0) {
      const t = setTimeout(() => window.print(), 500);
      return () => clearTimeout(t);
    }
  }, [loading, error, transactions.length]);

  if (loading) return <p style={{ padding: 24 }}>Loading transactions...</p>;
  if (error) return <p style={{ padding: 24 }}>Failed to load transactions.</p>;

  const categoryMap = new Map<string, Category>(categories.map((c) => [c.id, c]));

  const totalIncome = transactions
    .filter((t) => t.type === 'credit')
    .reduce((sum, t) => sum + t.amount_pesewas, 0);

  const totalExpenses = transactions
    .filter((t) => t.type === 'debit')
    .reduce((sum, t) => sum + t.amount_pesewas, 0);

  const dateRangeLabel = formatDateRange(from, to);

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: 24 }}>
      <h1>CediSense Transaction Export</h1>
      <p className="subtitle">{dateRangeLabel}</p>
      <p className="subtitle" style={{ marginTop: 4 }}>
        {transactions.length} transaction{transactions.length !== 1 ? 's' : ''}
      </p>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Counterparty</th>
            <th>Category</th>
            <th>Type</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {transactions.map((txn) => {
            const cat = txn.category_id ? categoryMap.get(txn.category_id) : undefined;
            const catLabel = cat ? `${cat.icon ?? ''} ${cat.name}`.trim() : '—';
            return (
              <tr key={txn.id}>
                <td style={{ whiteSpace: 'nowrap' }}>{formatDate(txn.transaction_date)}</td>
                <td>{txn.description ?? '—'}</td>
                <td>{txn.counterparty ?? '—'}</td>
                <td>{catLabel}</td>
                <td style={{ textTransform: 'capitalize' }}>{txn.type}</td>
                <td className={txn.type === 'credit' ? 'text-credit' : 'text-debit'}>
                  {txn.type === 'credit' ? '+' : '-'}
                  {formatPesewas(txn.amount_pesewas)}
                </td>
              </tr>
            );
          })}
          <tr className="total-row">
            <td colSpan={5}>Total Income</td>
            <td className="text-credit">+{formatPesewas(totalIncome)}</td>
          </tr>
          <tr className="total-row">
            <td colSpan={5}>Total Expenses</td>
            <td className="text-debit">-{formatPesewas(totalExpenses)}</td>
          </tr>
        </tbody>
      </table>

      <p style={{ marginTop: 32, fontSize: 10, color: '#999' }}>
        Generated by CediSense — Built by Hodges &amp; Co.
      </p>
    </div>
  );
}
