import type { CSVFormat } from '../types.js';

export const CSV_FORMATS: CSVFormat[] = [
  {
    provider: 'mtn_momo',
    label: 'MTN MoMo Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', amount: 'Amount', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'vodafone_cash',
    label: 'Vodafone Cash Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', amount: 'Amount', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'airteltigo',
    label: 'AirtelTigo Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', amount: 'Amount', reference: 'Ref', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'gcb_bank',
    label: 'GCB Bank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', debit: 'Debit', credit: 'Credit', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'ecobank',
    label: 'Ecobank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Narration', debit: 'Debit', credit: 'Credit', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD-Mon-YYYY',
  },
  {
    provider: 'fidelity_bank',
    label: 'Fidelity Bank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Trans Date', description: 'Description', debit: 'Debit', credit: 'Credit', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'stanbic_bank',
    label: 'Stanbic Bank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', debit: 'Debit', credit: 'Credit', reference: 'Reference No', balance: 'Balance' },
    dateFormat: 'YYYY-MM-DD',
  },
  {
    provider: 'absa_bank',
    label: 'Absa Bank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', amount: 'Amount', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'calbank',
    label: 'CalBank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Value Date', description: 'Narration', debit: 'Debit', credit: 'Credit', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'uba_bank',
    label: 'UBA Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Description', debit: 'Debit', credit: 'Credit', reference: 'Ref', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
  {
    provider: 'zenith_bank',
    label: 'Zenith Bank Statement',
    delimiter: ',',
    hasHeader: true,
    columnMap: { date: 'Date', description: 'Remarks', debit: 'Debit', credit: 'Credit', reference: 'Reference', balance: 'Balance' },
    dateFormat: 'DD/MM/YYYY',
  },
];
